require_relative 'base'

module Arli
  module Lock
    module Formats
      class Cmake < Base
        extension :cmake

        attr_accessor :libs, :comments

        def header
          @comments = []
          @libs = []
          "# vi:syntax=cmake"
        end

        def format(library)
          @libs << library
          @comments << "# Library #{library.name}:\n# version #{library.version}\n#    url: #{library.url}"
          nil
        end

        def footer
          %Q[
# This file is auto-generated by Arli library manager.
# See https://github.com/kigster/arli for more info.

set(ARLI_LIBRARIES_PATH "#{Arli.config.libraries.path}")
set(ARLI_LIBRARIES #{@libs.map(&:canonical_dir).join(' ')})

set(ARLI_LIBRARIES $ARLI_LIBRARIES PARENT_SCOPE)

#{@comments.join("\n")}
          ]
        end
      end
    end
  end
end
